# --- !Ups

CREATE TABLE "CUSTOMER" (
"LOGIN" VARCHAR(30) not null primary key,
"PWD_HASH" VARCHAR(105),
"ADMIN_PWD_HASH" VARCHAR(105),
"VALID_FROM" TIMESTAMP not null,
"VALID_UNTIL" TIMESTAMP not null,
"NUM_USERS" SMALLINT not null,
"STAEMME" VARCHAR(80)
);

# --- !Downs

DROP TABLE "CUSTOMER"
